### PR TITLE
Use pep 420

### PR DESCRIPTION
**Pull request by josecelano**

### CODE REVIEW

**Comment by josecelano** [comment]
hi @da2ce7 I removed all `__init__.py` files.

1. Production code worked fine without any change.
2. Tests did not work. It seems [PyTest does not support it](https://docs.pytest.org/en/6.2.x/goodpractices.html#tests-as-part-of-application-code) yet. But It worked after applying a patch.
3. `mypy` and `pylint` linters do not work. I have to found out if we can config them to sue namespace packages.

**Comment by josecelano** [comment]
`mypy` linter fixed. `pylint` seems to be [more complicated](https://github.com/PyCQA/pylint/issues/4057).

**Comment by josecelano** [comment]
`pylint` linting fixed thanks to https://github.com/PyCQA/pylint/issues/1524.

**Comment by josecelano** [comment]
@yeraydavidrodriguez we are going to use [PEP 420](https://www.python.org/dev/peps/pep-0420/) if it's possible from now on.

**Comment by yeraydavidrodriguez** [comment]
@josecelano great!

**Pull request merged**
